module PLLBlackBox (
    input  wire clock,     // 100 MHz input clock
    input  wire reset,         // Reset button (active high)
    output wire clk25MHz,
    output wire locked
);

    // PLL instantiation (generated by Clocking Wizard)
    clk_wiz_0 pll_inst (
        .clk_in1(clock),
        .reset(reset),
        .clk_out1(clk25MHz),
        .locked(locked)
    );

endmodule