name: sbt-tests
on:
  push:
    branches:
      - master
    paths:
      - '**/*.scala'
  pull_request:
    branches:
      - master
    paths:
      - '**/*.scala'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Run sbt tests
        run: nix develop . --command sbt test
